### ISSUE TITLE
Error when using post_mortem

### ISSUE THREAD

**Issue by matan-h** [cansarigol/pdbr#3] opened 2021-03-22 08:24 UTC
the code:
```python
import pdbr
import sys
try:
    1/0
except Exception:
    pdbr.post_mortem(sys.exc_info()[2])
```
raises the error:
```shell
Traceback (most recent call last):
  File "D:/Program Data/Pycharm/PycharmProjects/python_tell/ttt.py", line 8, in <module>
    1/0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Program Data/Pycharm/PycharmProjects/python_tell/ttt.py", line 10, in <module>
    pdbr.post_mortem(sys.exc_info()[2])
  File "D:\Program Data\Pycharm\PycharmProjects\python_tell\venv\lib\site-packages\pdbr\__main__.py", line 22, in post_mortem
    pdbr_cls().post_mortem(t)
  File "D:\Program Data\Pycharm\PycharmProjects\python_tell\venv\lib\site-packages\pdbr\utils.py", line 70, in pdbr_cls
    return klass()
  File "D:\Program Data\Pycharm\PycharmProjects\python_tell\venv\lib\site-packages\pdbr\_pdbr.py", line 55, in __init__
    super().__init__(**init_kwargs)
  File "D:\Program Data\Pycharm\PycharmProjects\python_tell\venv\lib\site-packages\IPython\terminal\debugger.py", line 32, in __init__
    self.pt_init(pt_session_options)
  File "D:\Program Data\Pycharm\PycharmProjects\python_tell\venv\lib\site-packages\IPython\terminal\debugger.py", line 74, in pt_init
    style=self.shell.style,
AttributeError: 'TerminalInteractiveShell' object has no attribute 'style'
```

**Comment by cansarigol** [comment] 2021-03-22 20:51
Thanks for pointing the issue out @matan-h

**Comment by matan-h** [comment] 2021-03-26 06:17
the issue still exists

**Comment by cansarigol** [comment] 2021-03-26 09:09
Thanks again and sorry about the issue. Could you share a bit more information with me since I didn't reproduce it? like your python, ipython and pdbr versions.

**Comment by matan-h** [comment] 2021-03-26 12:38
Python - 3.8.2
Ipython - 7.21.0
pdbr - 0.4.7
OS: windows 10

**Comment by matan-h** [comment] 2021-03-26 13:12
I reproduce it in pycharm venv

**Comment by cansarigol** [comment] 2021-03-28 14:51
@matan-h Could you check version 0.4.8? I believe I fixed the problem.

**Comment by matan-h** [comment] 2021-03-29 13:33
this error happens only in pycharm in windows after installing the last ipython, and then run the file from pycharm

**Comment by cansarigol** [comment] 2021-03-30 07:17
@matan-h I have no windows machine and I, therefore, use an emulator for it. I couldn't reproduce it anyway.

![Screenshot 2021-03-30 at 09 15 22](https://user-images.githubusercontent.com/5008696/112948739-b6713280-9138-11eb-8ce1-6806986a904a.png)

**Comment by matan-h** [comment] 2021-03-30 08:26
I tried with 3 different windows commuters. and all of them raise same error

**Comment by cansarigol** [comment] 2021-03-30 15:01
I checked some projects that are claimed with the same error. `simple_prompt` might be responsible for this error. In version 0.5.0 I forced its value as False even it is set by either ipython config or cli (`$pdbr --simple-prompt `)

**Comment by cansarigol** [comment] 2021-03-31 06:38
Could you try that suggestion in the below link? I wonder whether or not your error will be fixed.
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/406#issuecomment-483569596

**Closed** 2021-03-31 13:55 UTC
